In [1]:
import numpy as np

In [2]:
array1 = np.random.randint(10, 99, size=24)
array1

array([89, 96, 14, 25, 94, 55, 87, 34, 62, 57, 97, 55, 26, 42, 97, 54, 77,
       16, 11, 31, 19, 10, 65, 20])

In [3]:
array1 = array1.reshape(2, 3, 4)
array1

array([[[89, 96, 14, 25],
        [94, 55, 87, 34],
        [62, 57, 97, 55]],

       [[26, 42, 97, 54],
        [77, 16, 11, 31],
        [19, 10, 65, 20]]])

In [4]:
array1.dtype

dtype('int32')

In [5]:
array1.ndim

3

In [6]:
array2 = np.arange(10, 74, 4).reshape(4, -1)
array2

array([[10, 14, 18, 22],
       [26, 30, 34, 38],
       [42, 46, 50, 54],
       [58, 62, 66, 70]])

In [7]:
array3 = np.linspace(17, 39, num=16, dtype=int).reshape(4, 4)
array3

array([[17, 18, 19, 21],
       [22, 24, 25, 27],
       [28, 30, 31, 33],
       [34, 36, 37, 39]])

In [8]:
import random
array_con = np.concatenate((array2, array3 * 2 + random.randint(10, 18)), axis=1)
array_con

array([[10, 14, 18, 22, 46, 48, 50, 54],
       [26, 30, 34, 38, 56, 60, 62, 66],
       [42, 46, 50, 54, 68, 72, 74, 78],
       [58, 62, 66, 70, 80, 84, 86, 90]])

In [9]:
array_con.shape

(4, 8)

In [10]:
array_con.size

32

In [11]:
array4 = np.array([3, 4, 1, -8])
array4

array([ 3,  4,  1, -8])

In [12]:
array2 + array3

array([[ 27,  32,  37,  43],
       [ 48,  54,  59,  65],
       [ 70,  76,  81,  87],
       [ 92,  98, 103, 109]])

In [13]:
array1 + array4

array([[[ 92, 100,  15,  17],
        [ 97,  59,  88,  26],
        [ 65,  61,  98,  47]],

       [[ 29,  46,  98,  46],
        [ 80,  20,  12,  23],
        [ 22,  14,  66,  12]]])

In [14]:
array2 * array3

array([[ 170,  252,  342,  462],
       [ 572,  720,  850, 1026],
       [1176, 1380, 1550, 1782],
       [1972, 2232, 2442, 2730]])

In [15]:
array2 * array4

array([[  30,   56,   18, -176],
       [  78,  120,   34, -304],
       [ 126,  184,   50, -432],
       [ 174,  248,   66, -560]])

In [16]:
array3 * array4 - array2

array([[  41,   58,    1, -190],
       [  40,   66,   -9, -254],
       [  42,   74,  -19, -318],
       [  44,   82,  -29, -382]])

In [17]:
array1 / array4

array([[[29.66666667, 24.        , 14.        , -3.125     ],
        [31.33333333, 13.75      , 87.        , -4.25      ],
        [20.66666667, 14.25      , 97.        , -6.875     ]],

       [[ 8.66666667, 10.5       , 97.        , -6.75      ],
        [25.66666667,  4.        , 11.        , -3.875     ],
        [ 6.33333333,  2.5       , 65.        , -2.5       ]]])

In [18]:
array3 // array4 * 2

array([[ 10,   8,  38,  -6],
       [ 14,  12,  50,  -8],
       [ 18,  14,  62, -10],
       [ 22,  18,  74, -10]], dtype=int32)

In [19]:
array2[1:4, 1:] * array4[:3]

array([[ 90, 136,  38],
       [138, 200,  54],
       [186, 264,  70]])

In [20]:
array1

array([[[89, 96, 14, 25],
        [94, 55, 87, 34],
        [62, 57, 97, 55]],

       [[26, 42, 97, 54],
        [77, 16, 11, 31],
        [19, 10, 65, 20]]])

In [21]:
array1.size

24

In [22]:
array1.max()

97

In [23]:
array1.mean()

51.375

In [24]:
array1.max(axis=0) 

array([[89, 96, 97, 54],
       [94, 55, 87, 34],
       [62, 57, 97, 55]])

In [25]:
array1.max(axis=1) 

array([[94, 96, 97, 55],
       [77, 42, 97, 54]])

In [26]:
array1.max(axis=2) 

array([[96, 94, 97],
       [97, 77, 65]])

In [27]:
array1 = array1.reshape(4, -1)
array1

array([[89, 96, 14, 25, 94, 55],
       [87, 34, 62, 57, 97, 55],
       [26, 42, 97, 54, 77, 16],
       [11, 31, 19, 10, 65, 20]])

In [28]:
array1.max(axis=0) # в столбцах

array([89, 96, 97, 57, 97, 55])

In [29]:
array1.max(axis=1) # в строках

array([96, 97, 97, 65])

In [30]:
(array3 * array4 + array2).mean()

32.9375

In [31]:
(array1 * 2 - 23).min(axis=1)

array([ 5, 45,  9, -3])

In [32]:
array1.sum(axis=0)

array([213, 203, 192, 146, 333, 146])

In [33]:
array1[2].min()

16

In [34]:
if array1.max() > array2.max():
    print(f'max (array1, array2) = {array1.max()}')
else:
    print(f'max (array1, array2) = {array2.max()}')

max (array1, array2) = 97


In [35]:
print('max (array1, array_con) = ', end='')
if array1.max() > array_con.max():
    print(array1.max())
else:
    print(array_con.max())

max (array1, array_con) = 97


In [36]:
con2 = np.concatenate((array1, array2), axis=1)
con2

array([[89, 96, 14, 25, 94, 55, 10, 14, 18, 22],
       [87, 34, 62, 57, 97, 55, 26, 30, 34, 38],
       [26, 42, 97, 54, 77, 16, 42, 46, 50, 54],
       [11, 31, 19, 10, 65, 20, 58, 62, 66, 70]])

In [37]:
con2.mean(dtype=int)

46

In [38]:
round(con2.mean(), 3)

46.825